# Generated by Django 3.0.5 on 2020-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jionyeshe', '0003_auto_20200414_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
